apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-xalz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-xalz@sha256:1dd87996557579b51066516ac3c7099a26c63a543cdd0093ee2e6a665710c10b
        name: my-nodejs
        resources: {}
status: {}
